### ISSUE TITLE
Slide Mode wont work

### ISSUE THREAD

**Issue by b-reich** [hedgedoc/hedgedoc#879]
**Description**
When you open the Slide Mode the new browser window stays black.

**To Reproduce**
1. Create a new note
2. Insert some lorem ipsum
3. Click on Menu --> Slide Mode
4. See black site

**Expected behavior**
There should be nice slides.

**Additional context**
This happens on my self hosted instance and on [demo site](https://demo.hedgedoc.org)
Tested with Firefox and Chrome.
I am running the 1.7.2-alpine docker image.

**Comment by ErikMichelson** [comment]
This is caused by missing slide-options (#799). A bugfix is already merged to master and will be released soon.

**Comment by davidmehren** [comment]
Duplicate of #799

**Comment by ErikMichelson** [comment]
A workaround is to prepend your note with the following frontmatter (important is to just define `slideOptions` as an object).

```yaml
---
type: slide
slideOptions:
  a: 1
---
```

**Comment by b-reich** [comment]
> 
> 
> A workaround is to prepend your note with the following frontmatter (important is to just define `slideOptions` as an object).
> 
> ```yaml
> ---
> type: slide
> slideOptions:
>   a: 1
> ---
> ```

This is kinda broken for me. I got only a single slide with alle the content.

**Comment by DerMolly** [comment]
Could you maybe create an example note on the demo instance to let us have a look at this?

**Comment by b-reich** [comment]
@DerMolly 
It works on the demo server. https://demo.hedgedoc.org/NOw3tWnISmGUEKE9rj6jHQ#

On my private server it wont work. https://md.benjaminreich.de/ITBc-PDeTp2FEC7htFCSyQ#

**Comment by DerMolly** [comment]
Well as @ErikMichelson already said this is a known bug that was fixed with #799. Since 1.7.2 does not contain this fix it won't work on a 1.7.2 HedgeDoc.

**Comment by b-reich** [comment]
@DerMolly also broken on the demo server now

**Comment by b-reich** [comment]
@davidmehren the fix is already merged but I still have the issues.

**Comment by ErikMichelson** [comment]
I'm sorry but I can't reproduce this issue with your note on the demo instace with Chrome 89 on Ubuntu. Do you get any error messages in the developer console (F12 -> Console) while opening the presentation mode?
